config/routes.rb
Rails.application.routes.draw do

  #get 'ninja/index'
  #get 'ninja/show'
  #get 'ninja/new'
  #get 'ninja/edit'
  #get 'ninja/delete'
  root 'dojo#index'   #127.0.0.1:3000  => va a mostrar la página INDEX, define página por defecto o de inicio

  # get 'dojo/index'
  # get 'dojo/show'
  # get 'dojo/new'
  # get 'dojo/edit'
  # get 'dojo/delete'

  
    resources :dojo do
      member do
        get :delete
      end
    end

    resources :ninja do
      member do
        get :delete
      end
    end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dojo.rb
class Dojo < ApplicationRecord
    has_many :ninjas
    validates :nombre, :ciudad, :estado, presence: true
   validates :estado, length: {is: 2} 
    
    
end

app/models/ninja.rb
class Ninja < ApplicationRecord
  belongs_to :dojo
  validates :nombre, :apellido, presence: true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dojo_controller.rb
class DojoController < ApplicationController
  def index
    @dojos = Dojo.order(ciudad: :desc)
  end

  def show
    @dojo = Dojo.find(params[:id])
  end

  def new
  end

  def create 
  end

  def edit
  end

  def update 
  end

  def delete
  end

  def destroy 
  end
  
end

app/controllers/ninja_controller.rb
class NinjaController < ApplicationController
  def index
    @ninjas = Ninja.order('apellido desc')
  end

  def show
  end

  def new
  end

  def create 
  end

  def edit
  end

  def update 
  end

  def delete
  end

  def destroy 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dojo_helper.rb
module DojoHelper
end

app/helpers/ninja_helper.rb
module NinjaHelper
end

app/views/dojo/delete.html.erb
<h1>Dojo#delete</h1>
<p>Find me in app/views/dojo/delete.html.erb</p>

app/views/dojo/edit.html.erb
<h1>Dojo#edit</h1>
<p>Find me in app/views/dojo/edit.html.erb</p>

app/views/dojo/index.html.erb
<%# <h1>Dojo#index</h1> %>
<%# <p>Find me in app/views/dojo/index.html.erb</p> %>
<br>
<br>
<%= link_to "Enlace 18-O", new_dojo_path, :class=> "action new"%>

<table>
    <tr>
        <th>Nombre</th>        
        <th>Ciudad</th>
        <th>Estado</th>
        <th>Acciones</th>
    </tr>
        
    <% @dojos.each do |i| %>                  
    <tr>
        <td><%=i.nombre%></td>
        <td><%=i.ciudad%></td>
        <td><%=i.estado%></td>
        <td><%= link_to "Mostrar", dojo_path(i), :class=> "action show"%> </td>
    </tr>
    <% end %>

</table>
<br>
<!--<a href="dojo/new">Enlace 18-O</a> -->        <!--ESTÁTICO para el Public-->
<!--<a href="<%= new_dojo_path%>">Enlace 18-O</a> -->
<%# <%= link_to "Enlace 18-O", "dojo/new"%>     <!--DINÁMICO USAR RUBY-->
<%= link_to "Enlace 18-O", new_dojo_path%> 

<%# <%= 1+1 %> 
<%# <% pais ='Chile'%>
<%# <br> %>
<%# <%= "Hola #{pais}"%>
<%# <%7.times do |i|%>
<%# <p><%= i%></p>
<%# <%end%> 

app/views/dojo/new.html.erb
<h1>Dojo#new</h1>
<p>Find me in app/views/dojo/new.html.erb</p>

app/views/dojo/show.html.erb
<h1><%= @dojo.nombre%></h1>
<p><%= @dojo.ciudad%></p>
<p><%= @dojo.estado%></p>
<%= link_to "Volver", :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoNinjas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ninja/delete.html.erb
<h1>Ninja#delete</h1>
<p>Find me in app/views/ninja/delete.html.erb</p>

app/views/ninja/edit.html.erb
<h1>Ninja#edit</h1>
<p>Find me in app/views/ninja/edit.html.erb</p>

app/views/ninja/index.html.erb
<h1>Ninja#index</h1>
<p>Find me in app/views/ninja/index.html.erb</p>

<table>
    <tr>
        <th>Nombre</th>        
        <th>Apellido</th>
        <th>Dojo</th>
        <th>Acciones</th>
    </tr>
        
    <% @ninjas.each do |i| %>
                   
        
    <tr>
        <td><%=i.nombre%></td>
        <td><%=i.apellido%></td>
        <td><%=i.dojo_id%></td>
        <td></td>
    </tr>
    <% end %>

</table>

app/views/ninja/new.html.erb
<h1>Ninja#new</h1>
<p>Find me in app/views/ninja/new.html.erb</p>

app/views/ninja/show.html.erb
<h1>Ninja#show</h1>
<p>Find me in app/views/ninja/show.html.erb</p>